apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysqlchart.fullname" . }}-mysql
  labels:
  {{- include "mysqlchart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mysql
    {{- include "mysqlchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mysql
      {{- include "mysqlchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: keyvault-vega
              name: saname1
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mysql.mysql.image.repository }}:{{ .Values.mysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}