apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysqlchart.fullname" . }}-mysql
  labels:
  {{- include "mysqlchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    app: mysql
  {{- include "mysqlchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mysql.ports | toYaml | nindent 2 -}}